languge: python 3.7.1

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install codeclimate-test-reporter

env:
  - FLASK_VERSION=1.0.2

script:
  - pytest --cov=app/
  - coveralls

